version: "3.5"

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=controle
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d controle"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  api01:
    image: kauetsilva/picture-reader-image:latest
    hostname: api01
    environment:
      - POSTGRES_HOSTNAME=db
      - POSTGRES_PORT=5432
      - GEMINI_API_KEY=<ADICIONE SUA KEY>
      - DATABASE_URL=postgresql://admin:123@db:5432/controle
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
